export const SWITCH_TAB = 'SWITCH_TAB';

export const SHOP_REQUEST = 'SHOP_REQUEST';
export const SHOP_SUCCESS = 'SHOP_SUCCESS';
export const SHOP_FAILURE = 'SHOP_FAILURE';

export const SET_SHOP_DATA = 'SET_SHOP_DATA';

export const SERVICES_REQUEST = 'SERVICES_REQUEST';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_FAILURE = 'SERVICES_FAILURE';

export const SERVICE_REQUEST = 'SERVICE_REQUEST';
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS';
export const SERVICE_FAILURE = 'SERVICE_FAILURE';

export const SET_BOOKING_SERVICE = 'SET_BOOKING_SERVICE';
export const SET_BOOKING_CALENDAR_DATE = 'SET_BOOKING_CALENDAR_DATE';
export const SET_BOOKING_RANGE = 'SET_BOOKING_RANGE';

export const AVAILABLES_BOOKING_RANGES_REQUEST = 'AVAILABLES_BOOKING_RANGES_REQUEST';
export const AVAILABLES_BOOKING_RANGES_SUCCESS = 'AVAILABLES_BOOKING_RANGES_SUCCESS';
export const AVAILABLES_BOOKING_RANGES_FAILURE = 'AVAILABLES_BOOKING_RANGES_FAILURE';

//export const SHOW_MODAL_LOGIN = 'SHOW_MODAL_LOGIN';
//export const HIDE_MODAL_LOGIN = 'HIDE_MODAL_LOGIN';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ME_REQUEST = 'ME_REQUEST';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAILURE = 'ME_FAILURE';

export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const INCOMING_USER_BOOKINGS_REQUEST = 'INCOMING_USER_BOOKINGS_REQUEST';
export const INCOMING_USER_BOOKINGS_SUCCESS = 'INCOMING_USER_BOOKINGS_SUCCESS';
export const INCOMING_USER_BOOKINGS_FAILURE = 'INCOMING_USER_BOOKINGS_FAILURE';

export const SET_INCOMING_USER_BOOKINGS_VIEW = 'SET_INCOMING_USER_BOOKINGS_VIEW';

export const SET_INCOMING_USER_BOOKINGS_SEARCH_FILTER = 'SET_INCOMING_USER_BOOKINGS_SEARCH_FILTER';
export const SET_INCOMING_USER_BOOKINGS_STATUS_FILTER = 'SET_INCOMING_USER_BOOKINGS_STATUS_FILTER';
