export const RESET_PAGE_ERROR = 'RESET_PAGE_ERROR';
export const SET_PAGE_ERROR = 'SET_PAGE_ERROR';

export const SHOPS_REQUEST = 'SHOPS_REQUEST';
export const SHOPS_SUCCESS = 'SHOPS_SUCCESS';
export const SHOPS_FAILURE = 'SHOPS_FAILURE';

export const SHOP_REQUEST = 'SHOP_REQUEST';
export const SHOP_SUCCESS = 'SHOP_SUCCESS';
export const SHOP_FAILURE = 'SHOP_FAILURE';

export const SHOP_SERVICES_REQUEST = 'SHOP_SERVICES_REQUEST';
export const SHOP_SERVICES_SUCCESS = 'SHOP_SERVICES_SUCCESS';
export const SHOP_SERVICES_FAILURE = 'SHOP_SERVICES_FAILURE';

export const SHOP_SERVICE_REQUEST = 'SHOP_SERVICE_REQUEST';
export const SHOP_SERVICE_SUCCESS = 'SHOP_SERVICE_SUCCESS';
export const SHOP_SERVICE_FAILURE = 'SHOP_SERVICE_FAILURE';

export const SET_BOOKING_SERVICE = 'SET_BOOKING_SERVICE';
export const SET_BOOKING_CALENDAR_DATE = 'SET_BOOKING_CALENDAR_DATE';
export const SET_BOOKING_RANGE = 'SET_BOOKING_RANGE';

export const AVAILABLES_BOOKING_RANGES_REQUEST = 'AVAILABLES_BOOKING_RANGES_REQUEST';
export const AVAILABLES_BOOKING_RANGES_SUCCESS = 'AVAILABLES_BOOKING_RANGES_SUCCESS';
export const AVAILABLES_BOOKING_RANGES_FAILURE = 'AVAILABLES_BOOKING_RANGES_FAILURE';

export const BOOK_REQUEST = 'BOOK_REQUEST';
export const BOOK_SUCCESS = 'BOOK_SUCCESS';
export const BOOK_FAILURE = 'BOOK_FAILURE';

export const CLEAR_REGISTRATION = 'CLEAR_REGISTRATION';
export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';

export const SHOW_MODAL_LOGIN = 'SHOW_MODAL_LOGIN';
export const HIDE_MODAL_LOGIN = 'HIDE_MODAL_LOGIN';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ME_REQUEST = 'ME_REQUEST';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAILURE = 'ME_FAILURE';

export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const INCOMING_USER_BOOKINGS_REQUEST = 'INCOMING_USER_BOOKINGS_REQUEST';
export const INCOMING_USER_BOOKINGS_SUCCESS = 'INCOMING_USER_BOOKINGS_SUCCESS';
export const INCOMING_USER_BOOKINGS_FAILURE = 'INCOMING_USER_BOOKINGS_FAILURE';

export const SET_INCOMING_USER_BOOKINGS_VIEW = 'SET_INCOMING_USER_BOOKINGS_VIEW';

export const SET_INCOMING_USER_BOOKINGS_SEARCH_FILTER = 'SET_INCOMING_USER_BOOKINGS_SEARCH_FILTER';
export const SET_INCOMING_USER_BOOKINGS_STATUS_FILTER = 'SET_INCOMING_USER_BOOKINGS_STATUS_FILTER';

export const HISTORY_USER_BOOKINGS_REQUEST = 'HISTORY_USER_BOOKINGS_REQUEST';
export const HISTORY_USER_BOOKINGS_SUCCESS = 'HISTORY_USER_BOOKINGS_SUCCESS';
export const HISTORY_USER_BOOKINGS_FAILURE = 'HISTORY_USER_BOOKINGS_FAILURE';

export const SET_HISTORY_USER_BOOKINGS_PAGE = 'SET_HISTORY_USER_BOOKINGS_PAGE';
export const RESET_HISTORY_USER_BOOKINGS_PAGINATION = 'RESET_HISTORY_USER_BOOKINGS_PAGINATION';

export const SET_HISTORY_USER_BOOKINGS_SEARCH_FILTER = 'SET_HISTORY_USER_BOOKINGS_SEARCH_FILTER';

export const USER_BOOKING_REQUEST = 'USER_BOOKING_REQUEST';
export const USER_BOOKING_SUCCESS = 'USER_BOOKING_SUCCESS';
export const USER_BOOKING_FAILURE = 'USER_BOOKING_FAILURE';

export const ACTION_ON_USER_BOOKING_REQUEST = 'ACTION_ON_USER_BOOKING_REQUEST';
export const ACTION_ON_USER_BOOKING_SUCCESS = 'ACTION_ON_USER_BOOKING_SUCCESS';
export const ACTION_ON_USER_BOOKING_FAILURE = 'ACTION_ON_USER_BOOKING_FAILURE';

export const CLEAR_ACTION_ERROR_ON_USER_BOOKING = 'CLEAR_ACTION_ERROR_ON_USER_BOOKING';
